routes/web.php
<?php

use App\Http\Controllers\LoginController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RegisterController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::view('/register', 'register.index')->name('register.index');
Route::post('/register/store', [RegisterController::class, 'store'])->name('register.store');
Route::view('/', 'main.main')->name('main.index');
Route::view('register', 'register.index')->name('register.index');
Route::view('/login', 'login.index')->name('login.index');
Route::get('/logout', LogoutController::class)->name('logout');
Route::post('/login/store', [LoginController::class, 'store'])->name('login.store');

Route::patch('/profile/update/{id}', [ProfileController::class, 'update'])->name('profile.update');

Route::get('/profile/{id}', [ProfileController::class, 'index'])->name('profile.index');

Route::prefix('katalog')
    ->name('catalog.')
    ->controller(\App\Http\Controllers\CatalogController::class)
    ->group(function () {
        Route::get('/', 'index')->name('catalog');
        Route::get('/show/{id}', 'show')->name('show');
    });

Route::prefix('kontakts')
    ->name('kontakts.')
    ->controller(\App\Http\Controllers\ContactController::class)
    ->group(function () {
        Route::get('/', 'index')->name('kontakt');
        Route::post('/store', 'store')->name('store');
    });

Route::view('/korzina', 'korzina.korzina')->name('korzina.korzina');
Route::view('/kab', 'kab.kab')->name('kab.kab');

Route::prefix('admin')
    ->name('admin.')
    ->group(function () {
        Route::get('/', [\App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('index');

        Route::prefix('artist')
            ->name('artist.')
            ->controller(\App\Http\Controllers\Admin\ArtistController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/create', 'create')->name('create');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::post('/store', 'store')->name('store');
                Route::patch('/update/{id}', 'update')->name('update');
                Route::delete('/destroy/{id}', 'delete')->name('destroy');
            });

        Route::prefix('genre')
            ->name('genre.')
            ->controller(\App\Http\Controllers\Admin\GenreController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/create', 'create')->name('create');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::post('/store', 'store')->name('store');
                Route::patch('/update/{id}', 'update')->name('update');
                Route::delete('/destroy/{id}', 'delete')->name('destroy');
            });

        Route::prefix('album')
            ->name('album.')
            ->controller(\App\Http\Controllers\Admin\AlbumController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/create', 'create')->name('create');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::post('/store', 'store')->name('store');
                Route::patch('/update/{id}', 'update')->name('update');
                Route::delete('/destroy/{id}', 'delete')->name('destroy');
            });

        Route::prefix('contact')
            ->name('contact.')
            ->controller(\App\Http\Controllers\Admin\ContactController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::patch('/update', 'update')->name('update');
            });

        Route::prefix('user')
            ->name('user.')
            ->controller(\App\Http\Controllers\Admin\UserController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::post('/block/{id}', 'block')->name('block');
                Route::delete('/destroy', 'delete')->name('destroy');
            });

        Route::prefix('feedback')
            ->name('feedback.')
            ->controller(\App\Http\Controllers\Admin\FeedbackController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::delete('/delete/{id}', 'delete')->name('delete');
                Route::post('answer/{id}', 'answer')->name('answer');
            });

        Route::prefix('record')
            ->name('record.')
            ->controller(\App\Http\Controllers\Admin\RecordController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/create', 'create')->name('create');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::post('/store', 'store')->name('store');
                Route::patch('/update/{id}', 'update')->name('update');
                Route::delete('/destroy/{id}', 'delete')->name('destroy');
            });

        Route::prefix('record-music')
            ->name('record-music.')
            ->controller(\App\Http\Controllers\Admin\RecordMusicController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/create', 'create')->name('create');
                Route::post('/store', 'store')->name('store');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::delete('/delete/{id}', 'delete')->name('destroy');
            });
    });

app/Models/Feedback.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Feedback extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'email',
        'description'
    ];
}

app/Http/Controllers/Admin/FeedbackController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Feedback;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class FeedbackController extends Controller
{
    public function index ()
    {
        return view('admin.feedback.index', [
            'feedbacks' => Feedback::all()
        ]);
    }

    public function edit (Feedback $id) {
        return view('admin.feedback.edit', [
            'feedback' => $id
        ]);
    }

    public function answer (int $id, Request $request) {
        Mail::send('admin.verification.question', ['question' => Feedback::find($id)->description,
            'otvet' => $request->message], function ($message) use ($id) {
            $message->to(Feedback::find($id)->email, 'Домашний уют')->subject
            ('Домашний уют');
            $message->from('lioshakhirny@gmail.com', 'Домашний уют');
        });

        Feedback::query()->find($id)->delete();

        return redirect()->route('admin.feedback.index')->with('Ответ отправлен на почту');
    }
}

resources/views/admin/feedback/edit.blade.php
@extends('layouts.admin.main')
@section('content')
    <div class="page-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-header pb-0">
                            <h4>Ответ на вопрос</h4>
                            <br>
                            <p> Вопрос:
                                {{$feedback->description}}
                            </p>
                        </div>
                        <form method="post" action="{{route('admin.feedback.answer', ['id' => $feedback->id])}}" class="form theme-form">
                            @csrf
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        <div class="mb-3">
                                            <label class="form-label" for="exampleFormControlInput1">Ответ на вопрос</label>
                                            <textarea class="form-control" placeholder="Описание о нас" name="message" cols="30" rows="30">
                                            </textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer text-end">
                                <button class="btn btn-primary" type="submit">Отправить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/feedback/index.blade.php
@extends('layouts.admin.main')
@section('content')
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-title">
                <div class="row">
                    <div class="col-sm-6">
                        <h3>Обратная связь</h3>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{route('admin.index')}}"><i data-feather="home"></i></a></li>
                            <li class="breadcrumb-item">Обратная связь</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <!-- Container-fluid starts-->
        <div class="container-fluid basic_table">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Список</h4>
                        </div>
                        <div class="table-responsive theme-scrollbar">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th scope="col">Id</th>
                                    <th scope="col">Имя</th>
                                    <th scope="col">Почта</th>
                                    <th scope="col">Действия</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($feedbacks as $feedback)
                                    <tr>
                                        <th scope="row">{{$feedback->id}}</th>
                                        <td>{{$feedback->name}}</td>
                                        <td>{{$feedback->email}}</td>
                                        <td>
                                            <a href="{{route('admin.feedback.edit', ['id' => $feedback->id])}}">Ответить</a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection